export const SEO_REQUEST = "SEO_REQUEST";
export const SEO_SUCCESS = "SEO_SUCCESS";
export const SEO_FAIL = "SEO_FAIL";

export const CREATE_SEO_REQUEST = "CREATE_SEO_REQUEST";
export const CREATE_SEO_SUCCESS = "CREATE_SEO_SUCCESS";
export const CREATE_SEO_FAIL = "CREATE_SEO_FAIL";
export const CREATE_SEO_RESET = "CREATE_SEO_RESET";

export const UPDATE_SEO_REQUEST = "UPDATE_SEO_REQUEST";
export const UPDATE_SEO_SUCCESS = "UPDATE_SEO_SUCCESS";
export const UPDATE_SEO_FAIL = "UPDATE_SEO_FAIL";
export const UPDATE_SEO_RESET = "UPDATE_SEO_RESET";

export const SINGLE_PAGE_SEO_REQUEST = "SINGLE_PAGE_SEO_REQUEST";
export const SINGLE_PAGE_SEO_SUCCESS = "SINGLE_PAGE_SEO_SUCCESS";
export const SINGLE_PAGE_SEO_FAIL = "SINGLE_PAGE_SEO_FAIL";

export const SEO_CLEAR_SEO = "SEO_CLEAR_SEO";
