export const EMAIL_SUBSCRIPTION_REQUEST = "EMAIL_SUBSCRIPTION_REQUEST";
export const EMAIL_SUBSCRIPTION_SUCCESS = "EMAIL_SUBSCRIPTION_SUCCESS";
export const EMAIL_SUBSCRIPTION_FAIL = "EMAIL_SUBSCRIPTION_FAIL";
export const EMAIL_SUBSCRIPTION_RESET = "EMAIL_SUBSCRIPTION_RESET";
export const SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR";
